routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['web', 'cekuser:1']],
function(){
  Route::get('kategori/data', 'KategoriController@listData')->name('kategori.data');
  Route::resource('kategori', 'KategoriController');

  Route::get('produk/data', 'ProdukController@listData')->name('produk.data');
  Route::post('produk/hapus', 'ProdukController@deleteSelected');
  Route::post('produk/cetak', 'ProdukController@printBarcode');
  Route::resource('produk', 'ProdukController');

  Route::get('supplier/data', 'SupplierController@listData')->name('supplier.data');
  Route::resource('supplier', 'SupplierController');

  Route::get('member/data', 'MemberController@listData')->name('member.data');
  Route::resource('member/cetak', 'MemberController@printCard');
  Route::resource('member', 'MemberController');

  Route::get('pengeluaran/data', 'PengeluaranController@listData')->name('pengeluaran.data');
  Route::resource('pengeluaran', 'PengeluaranController');
});

app/Produk.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Produk extends Model
{
    protected $table = 'produk';
    protected $primaryKey = 'id_produk';

    public function kategori(){
      return $this->belongsTo('App\Kategori');
    }
}

app/Http/Controllers/ProdukController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Produk;
use App\Kategori;
use Datatables;
use PDF;

class ProdukController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $kategori = Kategori::all();
        return view('produk.index', compact('kategori'));
    }

    public function listData()
    {
        $produk = Produk::leftJoin('kategori', 'kategori.id_kategori', '=', 'produk.id_kategori')
        ->orderBy('produk.id_produk', 'desc')->get();
        $no = 0;
        $data = array();
        foreach ($produk as $list) {
            $no ++;
            $row = array();
            $row[] = "<input type='checkbox' name='id[]' value='".$list->id_produk."'>";
            $row[] = $no;
            $row[] = $list->kode_produk;
            $row[] = $list->nama_produk;
            $row[] = $list->nama_kategori;
            $row[] = $list->merk;
            $row[] = "Rp. ".format_uang($list->harga_beli);
            $row[] = "Rp. ".format_uang($list->harga_jual);
            $row[] = $list->diskon."%";
            $row[] = $list->stok;
            $row[] = "<div class='btn-group'><a onclick='editForm(".$list->id_produk.")'
            class='btn btn-primary btn-sm'><i class='fa fa-pencil-alt'></i></a>
            <a onclick='deleteData(".$list->id_produk.")' class='btn btn-danger'><i class='fa fa-trash'></i>
            </a></div>";
            $data[] = $row;
        }

        return DataTables()->of($data)->escapeColumns([])->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $jml = Produk::where('kode_produk', '=', $request['kode'])->count();

      if($jml < 1){
        $produk = new Produk;
        $produk->kode_produk = $request['kode'];
        $produk->nama_produk = $request['nama'];
        $produk->id_kategori = $request['kategori'];
        $produk->merk = $request['merk'];
        $produk->harga_beli = $request['harga_beli'];
        $produk->diskon = $request['diskon'];
        $produk->harga_jual = $request['harga_jual'];
        $produk->stok = $request['stok'];
        $produk->save();

        echo json_encode(array('msg'=>'success'));
      }else {
        echo json_encode(array('msg'=>'error'));
      }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $produk = Produk::find($id);
        echo json_encode($produk);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $produk = Produk::find($id);

      $produk->nama_produk = $request['nama'];
      $produk->id_kategori = $request['kategori'];
      $produk->merk = $request['merk'];
      $produk->harga_beli = $request['harga_beli'];
      $produk->diskon = $request['diskon'];
      $produk->harga_jual = $request['harga_jual'];
      $produk->stok = $request['stok'];
      $produk->update();

      echo json_encode(array('msg'=>'success'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $produk = Produk::find($id);
      $produk->delete();
    }

    public function deletedSelected(Request $request)
    {
      foreach ($request['id'] as $id) {
        $produk = Produk::find($id);
        $produk->delete();
      }
    }

    public function printBarcode(Request $request)
    {
      $dataproduk = array();
      foreach ($request['id'] as $id) {
        $produk = Produk::find($id);
        $dataproduk[] = $produk;
      }
      $no = 1;
      $pdf = PDF::loadView('produk.barcode', compact('dataproduk', 'no'));
      $pdf->setPaper('a4', 'potrait');
      return $pdf->stream();
    }
}

resources/views/Produk/barcode.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Cetak Barcode</title>
</head>
<body>

    <table width="100%">
        <tr>
            @foreach($produk as $data)
            <td align="center" style="border: 1px solid #ccc">
                {{ $data->nama_produk }} - Rp. {{ format_uang($data->harga_jual) }}<br>
                <img src="data:image/png;base64,{{ DNS1D::getBarcodePNG($data->kode_produk, 'C39') }}"
                height="60" width="180">
                <br>{{ $data->kode_produk }}
            </td>
            @if( $no++ % 3 == 0)
        </tr><tr>
            @endif
            @endforeach
        </tr>
    </table>

</body>
</html>

resources/views/Produk/form.blade.php
	<div class="modal" id="modal-form" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
		<div class="modal-dialog modal-lg">
			<div class="modal-content">
				<form action="" class="form-horizontal" data-toggle="validator" method="post">
					{{ csrf_field() }} {{ method_field('POST') }}

					<div class="modal-header">
						<button aria-label="Close" data-dismiss="modal" class="close" type="button">
              <span aria-hidden="true"> &times; </span></button>
						<h3 class="modal-title"></h3>
						<hr>
					</div>

					<div class="modal-body">

					  	<input type="hidden" id="id" name="id">
					  	<div class="form-group">
								<label for="kode" class="col-md-3 control-label">Kode Produk</label>
    						<div class="col-md-6">
                  <input id="kode" type='number' class="form-control" name="kode" autofocus required/>
                  <span class="help-block with-errors"></span>
    						</div>
							</div>

						<div class="form-group">
							<label for="nama" class="col-md-3 control-label">Nama Produk</label>
							<div class="col-md-6">
								<input id="nama" type='text' class="form-control"  name="nama" autofocus required/>
								<span class="help-block with-errors"></span>
							</div>
						</div>

						<div class="form-group">
							<label for="kategori" class="col-md-3 control-label">Kategori</label>
							<div class="col-md-6">
								<select class="form-control" type="text" id="kategori" name="kategori" required>
									<option value="">-- Pilih Kategori --</option>
									@foreach ($kategori as $list)
										<option value="{{ $list->id_kategori }}">{{ $list->nama_kategori }}</option>
									@endforeach
								</select>
								<span class="help-block with-errors"></span>
							</div>
					</div>

					<div class="form-group">
						<label for="merk" class="col-md-3 control-label">Merk</label>
						<div class="col-md-6">
							<input id="merk" type='text' class="form-control" name="merk" required/>
							<span class="help-block with-errors"></span>
						</div>
					</div>

					<div class="form-group">
						<label for="harga_beli" class="col-md-3 control-label">Harga Beli</label>
						<div class="col-md-3">
							<input id="harga_beli" type='text' class="form-control" name="harga_beli" required/>
							<span class="help-block with-errors"></span>
						</div>
					</div>

					<div class="form-group">
						<label for="diskon" class="col-md-3 control-label">Diskon</label>
						<div class="col-md-3">
							<input id="diskon" type='text' class="form-control" name="diskon" required/>
							<span class="help-block with-errors"></span>
						</div>
					</div>

					<div class="form-group">
						<label for="harga_jual" class="col-md-3 control-label">Harga Jual</label>
						<div class="col-md-3">
							<input id="harga_jual" type='text' class="form-control" name="harga_jual" required/>
							<span class="help-block with-errors"></span>
						</div>
					</div>

					<div class="form-group">
						<label for="stok" class="col-md-3 control-label">Stok</label>
						<div class="col-md-2">
							<input id="stok" type='text' class="form-control" name="stok" required/>
							<span class="help-block with-errors"></span>
						</div>
					</div>

					<div class="modal-footer">
						<button type="submit" class="btn btn-primary btn-save"> <i class="fa fa-floppy-o"></i> Simpan</button>
						<button class="btn btn-warning" data-dismiss="modal" type="button"> <i class="fa fa-arrow-circle-left"></i>
              Batal</button>
					</div>
				</form>

			</div>
		</div>
	</div>

resources/views/Produk/index.blade.php
@extends('layouts.app')

@section('title')
  Daftar Produk
@endsection

@section('breadcrumb')
  @parent
  <li>produk</li>
@endsection

@section('content')
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <a onclick="addForm()" class="btn btn-success"> <i class="fa fa-plus-circle"></i> Tambah</a>
          <a onclick="deleteAll()" class="btn btn-danger"> <i class="fa fa-trash"></i> Hapus</a>
          <a onclick="printBarcode()" class="btn btn-info"> <i class="fa fa-barcode"></i> Cetak Barcode</a>
        </div>

        <div class="box-body">

          <form action="index.html" method="post">
            {{ csrf_field() }}
            <table class="table table-striped">
              <thead>
                <tr>
                  <th width="20"><input type="checkbox" value="1" id="select-all"></th>
                  <th width="20">No</th>
                  <th>Kode Produk</th>
                  <th>Nama Produk</th>
                  <th>Kategori</th>
                  <th>Merk</th>
                  <th>Harga Beli</th>
                  <th>Harga Jual</th>
                  <th>Diskon</th>
                  <th>Stok</th>
                  <th width="100">Aksi</th>
                </tr>
              </thead>
              <tbody></tbody>
            </table>
          </form>

        </div>

      </div>
    </div>
  </div>
@include('produk.form')
@endsection

@section('script')
<script type="text/javascript">
  var table, save_method;
  $(function(){
    //Menampilkan data dengan plugin DataTable
    table = $('.table').DataTable({
      "processing" : true,
      "serverside" : true,
      "ajax" : {
        "url" : "{{ route('produk.data') }}",
        "type" : "GET"
      },
      'columnDefs' : [{
        'targets': 0,
        'searchable': false,
        'orderable': false
      }],
      'order': [1, 'asc']
    });

    // Centak semua checkbox ketika checkbox dengan id #select-all dicentang
    $('#select-all').click(function(){
      $('input[type="checkbox"]').prop('checked', this.checked);
    });

    //Menyimpan data dari form tambah/edit beserta validasinya
    $('#modal-form form').validator().on('submit', function(e){
      if(!e.isDefaultPrevented()){
        var id = $('#id').val();
        if(save_method == "add") url = "{{ route('produk.store') }}";
        else url = "produk/"+id;

        $.ajax({
          url : url,
          type : "POST",
          data : $('#modal-form form').serialize(),
          dataType : 'JSON',
          success : function(data){
            if(data.msg=="error"){
              alert('Kode produk sudah digunakan!');
              $('#kode').focus().select();
            }else {
              $('#modal-form').modal('hide');
              table.ajax.reload();
            }
          },
          error : function(){
            alert("Tidak dapat menyimpan data!");
          }
        });
        return false;
      }
    });
  });

//Menampilkan form tambah
function addForm(){
	save_method = "add";
	$('input[name=_method]').val('POST');
	$('#modal-form').modal('show');
	$('#modal-form form')[0].reset();
	$('.modal-title').text('Tambah Kategori');
}

//Menampilkan form edit dan menampilkan data pada form tersebut
function editForm(id){
	save_method = "edit";
	$('input[name=_method').val('PATCH');
	$('#modal-form form')[0].reset();
	$.ajax({
		url : "kategori/"+id+"/edit",
		type : "GET",
		dataType : "JSON",
		success : function(data){
			$('#modal-form').modal('show');
			$('.pmd-card-title-text').text('Edit Kategori');

			$('#id').val(data.id_kategori);
			$('#nama').val(data.nama_kategori);
		},
		error : function(){
			alert("Tidak dapat menampilkan data!");
		}
	});
}

//Menghapus data
function deleteData(id){
	if(confirm("Apakah yakin data akan dihapus?")){
		$.ajax({
			url : "kategori/"+id,
			type : "POST",
      data : {'_method' : 'DELETE', '_token' : $('meta[name=csrf-token]').attr('content')},
			success : function(data){
        table.ajax.reload();
			},
			error : function(){
				alert("Tidak dapat menghapus data!");
			}
		});
	}
}

//Menghapus semua data yang dicentang
function deleteAll(){
  if($('input:checked').length < 1){
    alert('Pilih data yang akan dihapus!');
  }else if(confirm("Apakah yakin akan menghapus semua data terpilih?")){
    $.ajax({
      url : "produk/hapus",
      type : "POST",
      data : {' _method' : 'DELETE', '_token' : $('meta[name=csrf-token]').attr('content')},
      success : function (data){
        table.ajax.reload();
      },
      error : function(){
        alert("Tidak dapat menghapus data!");
      }
    });
  }
}

//Mencetak barcode ketika tombol Cetak Barcode diklik
function printBarcode({
  if($('input.:checked').length < 1){
    alert('Pilih data yang akan dicetak!');
  }else{
    $('#form-produk').attr('target', '_blank').attr('action', "produk/cetak").submit();
  }
});
</script>
@endsection