routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['web', 'cekuser:1']],
function(){
  Route::get('kategori/data', 'KategoriController@listData')->name('kategori.data');
  Route::resource('kategori', 'KategoriController');

  Route::get('produk/data', 'ProdukController@listData')->name('produk.data');
  Route::post('produk/hapus', 'ProdukController@deleteSelected');
  Route::post('produk/cetak', 'ProdukController@printBarcode');
  Route::resource('produk', 'ProdukController');

  Route::get('supplier/data', 'SupplierController@listData')->name('supplier.data');
  Route::resource('supplier', 'SupplierController');

  Route::get('member/data', 'MemberController@listData')->name('member.data');
  Route::resource('member/cetak', 'MemberController@printCard');
  Route::resource('member', 'MemberController');

  Route::get('pengeluaran/data', 'PengeluaranController@listData')->name('pengeluaran.data');
  Route::resource('pengeluaran', 'PengeluaranController');
});

app/Member.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Member extends Model
{
  protected $table = 'member';
  protected $primaryKey = 'id_member';

  public function penjualan(){
    return $this->hasMany('App\Penjualan', 'id_supplier');
  }
}

app/Http/Controllers/MemberController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Member;
use PDF;

class MemberController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('member.index');
    }

    public function listData(){
      $member = Member::orderBy('id_member', 'desc')->get();
      $no = 0;
      $data = array();
      foreach($member as $list){
        $no ++;
        $row = array();
        $row[] = "<input type='checkbox' name='id[]''value='".$list->id_member."'>";
        $row[] = $no;
        $row[] = $list->kode_member;
        $row[] = $list->nama;
        $row[] = $list->alamat;
        $row[] = $list->telpon;
        $row[] = '<div class="btn-group">
          <a onclick="editForm('.$list->id_member.')" class="btn btn-primary btn-sm">
            <i class="fa fa-pencil-alt"></i></a>
            <a onclick="deleteData('.$list->id_member.')" class="btn btn-danger btn-sm">
            <i class="fa fa-trash"></i></a>
        </div>';
        $data[] = $row;
      }

      $output = array("data" => $data);
      return response()->json($output);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $jml = Member::where('kode_member', '=', $request['kode'])->count();
      if($jml < 1){
        $member = new Member;
        $member->kode_member = $request['kode'];
        $member->nama = $request['nama'];
        $member->alamat = $request['alamat'];
        $member->telpon = $request['telpon'];
        $member->save();
        echo json_encode(array('msg'=>'success'));
      }else{
      echo json_encode(array('msg'=>'error'));
      }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $member = Member::find($id);
        echo json_encode($member);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $member = Memer::find($id);
      $member->nama = $request['nama'];
      $member->alamat = $request['alamat'];
      $member->telpon = $request['telpon'];
      $member->update();
      echo json_encode(array('msg'=>'success'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $member = Member::find($id);
        $member->delete();
    }

    public function printCard(Request $request)
    {
      $datamember = array();
      foreach($request['id'] as $id){
        $member = Member::find($id);
        $datamember[] = $member;
      }

      $pdf = PDF::loadView('member.card', compact('datamember'));
      $pdf->setPaper(array(0, 0, 566.93, 850.39), 'potrait');
      return $pdf->stream();
    }
}

resources/views/member/card.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Cetak Kartu Member</title>

    <style>
      .box{position: relative;;}
      .card{ width: 501.732pt; height: 147.402pt;}
      .kode{
        position: absolute;
        top: 110pt;
        left: 10pt;
        color: #fff;
        font-size: 15pt;
      }
      .barcode{
        position: absolute;
        top: 15pt;
        left: 280pt;
        font-size: 10pt;
      }
    </style>
</head>
<body>

    <table width="100%">
        @foreach(datamember as $data)
          <tr>
            <td align="center">
              <div class="box">
                <img src="{{ asset('public/images/card.png') }}"
                class="card">
                <div class="kode">{{ $data->kode_member }}</div>
                <div class="barcode">
                  <img src="data:image/png;base64,{{ DNS1D::getBarcodePNG( $data->kode_member, 'C39') }}" height="30" width="130">
                  <br>{{ $data->kode_member }}
                </div>
              </div>
            </td>
          </tr>
        @endforeach
    </table>
</body>
</html>

resources/views/member/form.blade.php
	<div class="modal" id="modal-form" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
		<div class="modal-dialog modal-lg">
			<div class="modal-content">
				<form action="" class="form-horizontal" data-toggle="validator" method="post">
					{{ csrf_field() }} {{ method_field('POST') }}

					<div class="modal-header">
						<button aria-label="Close" data-dismiss="modal" class="close" type="button">
              <span aria-hidden="true"> &times; </span></button>
						<h3 class="modal-title"></h3>
						<hr>
					</div>

					<div class="modal-body">

				  	<input type="hidden" id="id" name="id">
				  	<div class="form-group">
							<label for="kode" class="col-md-3 control-label">Kode Member</label>
  						<div class="col-md-6">
                <input id="kode" type='number' class="form-control" name="kode" autofocus required/>
                <span class="help-block with-errors"></span>
  						</div>
						</div>

						<div class="form-group">
							<label for="nama" class="col-md-3 control-label">Nama</label>
							<div class="col-md-8">
								<input id="nama" type='text' class="form-control" name="nama" required/>
								<span class="help-block with-errors"></span>
							</div>
					</div>

					<div class="form-group">
						<label for="alamat" class="col-md-3 control-label">Alamat</label>
						<div class="col-md-6">
							<input id="alamat" type='text' class="form-control" name="alamat"  autofocus required/>
							<span class="help-block with-errors"></span>
						</div>
					</div>

					<div class="form-group">
						<label for="telpon" class="col-md-3 control-label">Telpon</label>
						<div class="col-md-6">
							<input id="telpon" type='text' class="form-control" name="telpon"  autofocus required/>
							<span class="help-block with-errors"></span>
						</div>
					</div>

					<div class="modal-footer">
						<button type="submit" class="btn btn-primary btn-save"> <i class="fa fa-floppy-o"></i> Simpan</button>
						<button class="btn btn-warning" data-dismiss="modal" type="button"> <i class="fa fa-arrow-circle-left"></i>
              Batal</button>
					</div>
				</form>

			</div>
		</div>
	</div>

resources/views/member/index.blade.php
@extends('layouts.app')

@section('title')
  Daftar Member
@endsection

@section('breadcrumb')
  @parent
  <li>member</li>
@endsection

@section('content')
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <a onclick="addForm()" class="btn btn-success"> <i class="fa fa-plus-circle"></i> Tambah</a>
          <a onclick="printCard()" class="btn btn-info"> <i class="fa fa-credit-card"></i> Cetak Kartu</a>
        </div>

        <div class="box-body">

          <form method="post" id="form-member">
            {{ csrf_field() }}
            <table class="table table-striped">
              <thead>
                <tr>
                  <th width="20"><input type="checkbox" value="1" id="select-all"></th>
                  <th width="20">No</th>
                  <th>Kode Member</th>
                  <th>Nama Member</th>
                  <th>Alamat</th>
                  <th>Telpon</th>
                  <th width="100">Aksi</th>
                </tr>
              </thead>
              <tbody></tbody>
            </table>
          </form>

        </div>

      </div>
    </div>
  </div>
@include('member.form')
@endsection

@section('script')
<script type="text/javascript">
  var table, save_method;
  $(function(){
    //Menampilkan data dengan plugin DataTable
    table = $('.table').DataTable({
      "processing" : true,
      "ajax" : {
        "url" : "{{ route('member.data') }}",
        "type" : "GET"
      },
      'columnDefs' : [{
        'targets': 0,
        'searchable': false,
        'orderable': false
      }],
      'order': [1, 'asc']
    });

    // Centak semua checkbox ketika checkbox dengan id #select-all dicentang
    $('#select-all').click(function(){
      $('input[type="checkbox"]').prop('checked', this.checked);
    });

    //Menyimpan data dari form tambah/edit
    $('#modal-form form').validator().on('submit', function(e){
      if(!e.isDefaultPrevented()){
        var id = $('#id').val();
        if(save_method == "add") url = "{{ route('member.store') }}";
        else url = "member/"+id;

        $.ajax({
          url : url,
          type : "POST",
          data : $('#modal-form form').serialize(),
          dataType : 'JSON',
          success : function(data){
            if(data.msg=="error"){
              alert('Kode member sudah digunakan!');
              $('#kode').focus().select();
            }else{
              $('#modal-form').modal('hide');
              table.ajax.reload();
            }
          },
          error : function(){
            alert("Tidak dapat menyimpan data!");
          }
        });
        return false;
      }
    });
  });

//Menampilkan form tambah
function addForm(){
	save_method = "add";
	$('input[name=_method]').val('POST');
	$('#modal-form').modal('show');
	$('#modal-form form')[0].reset();
	$('.modal-title').text('Tambah Member');
  $('#kode').attr('readonly', false);
}

//Menampilkan form edit dan menampilkan data pada form tersebut
function editForm(id){
	save_method = "edit";
	$('input[name=_method').val('PATCH');
	$('#modal-form form')[0].reset();
	$.ajax({
		url : "member/"+id+"/edit",
		type : "GET",
		dataType : "JSON",
		success : function(data){
			$('#modal-form').modal('show');
      $('#modal-title').text('Edit Member');

			$('#id').val(data.id_member);
      $('#kode').val(data.kode_member).attr('readonly', true);
			$('#nama').val(data.nama);
      $('#alamat').val(data.alamat);
      $('#telpon').val(data.telpon);
		},
		error : function(){
			alert("Tidak dapat menampilkan data!");
		}
	});
}

//Menghapus data
function deleteData(id){
	if(confirm("Apakah yakin data akan dihapus?")){
		$.ajax({
			url : "member/"+id,
			type : "POST",
      data : {'_method' : 'DELETE', '_token' : $('meta[name=csrf-token]').attr('content')},
			success : function(data){
        table.ajax.reload();
			},
			error : function(){
				alert("Tidak dapat menghapus data!");
			}
		});
	}
}

//Mencetak kartu ketika tombol Cetak kartu diklik
function printCard(){
  if($('input:checked').length < 1){
    alert('Pilih data yang akan dicetak!');
  }else{
    $('#form-member').attr('target', '_blank').attr('action', "member/cetak").submit();
  }
}
</script>
@endsection